name: AOC pipeline
run-name: Run AOC solutions
on:
    push: 
        branches: 
            - main
    schedule:
        - cron: "0 0 * * *"
jobs:
    run_csharp:
        name: Run C# solutions
        defaults:
            run:
                working-directory: "./C#"
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Install Dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.x'
            - name: Run solutions
              run: dotnet test --logger "console;verbosity=detailed"

