name: AOC pipeline
run-name: Run AOC solutions
on:
    push: 
        branches: 
            - main
    schedule:
        - cron: "0 0 * * *"
jobs:
    run_csharp:
        name: Run C# solutions
        defaults:
            run:
                working-directory: "./C#"
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Install Dotnet 9.x
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.x'
            - name: Run solutions
              run: dotnet test --logger "console;verbosity=detailed"

    run_go:
        name: Run Go solutions
        defaults:
            run:
                working-directory: "./Go"
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Install Go 1.19.8
              uses: actions/setup-go@v5
              with:
                go-version: '1.19.8'
            - name: Run solutions
              run: find . -regex ".*\.go" | xargs go run

